# -*- mode: ruby -*-
# vi: set ft=ruby :

UBUNTU_BOX    = "bento/ubuntu-24.04"
PROVIDER      = "virtualbox"
VM_NAME       = "server-nfs"
VM_HOSTNAME   = "nfs.storage.srv"
VM_IP_ADDRESS = "192.168.56.9"

Vagrant.configure("2") do |config|
  config.vm.box = UBUNTU_BOX
  config.vm.hostname = VM_HOSTNAME
  config.vm.network "private_network", ip: VM_IP_ADDRESS
  config.vm.synced_folder "shared/", "/home/vagrant/shared"

  config.vm.provider PROVIDER do |vb|
    vb.name   = VM_NAME
    vb.memory = 2144
    vb.cpus   = 4
  end

  config.vm.provision "ansible" do |ansible|
        ansible.playbook = "shared/server.yaml"
      end
end
