# -*- mode: ruby -*-
# vi: set ft=ruby :

UBUNTU_BOX        = "bento/ubuntu-24.04"
IP_BASE           = "192.168.56."
K8S_NAME          = "dev-k8s"
K8S_KEY_VERSION   = "1.33"
K8S_TOOLS_VERSION = "1.33.*"
OS_VERSION        = "xUbuntu_22.04"
CRIO_VERSION      = "1.28"
CALICO_VERSION    = "3.29.2"
ANSIBLE_BASE_PATH = "ansible/playbooks/k8s"

MASTERS = [
	{:hostname => 'server-k8s-master-', :box => UBUNTU_BOX, :memory => 2048, :cpus => 2}
]

WORKERS = [
	{:hostname => 'server-k8s-node-', :box => UBUNTU_BOX, :memory => 4096, :cpus => 3},
	{:hostname => 'server-k8s-node-', :box => UBUNTU_BOX, :memory => 4096, :cpus => 3}
]

Vagrant.configure("2") do |config|
	config.ssh.insert_key = false

	MASTERS.to_enum.with_index(1).each do |machine, i|
		config.vm.define "#{machine[:hostname]}#{i}" do |master|
			master.vm.box = machine[:box]
			master.vm.network "private_network", ip: "#{IP_BASE}#{i + 11}"
			master.vm.hostname = "#{machine[:hostname]}#{i}"
			
			master.vm.provider "virtualbox" do |vbx|
			vbx.name   = "#{machine[:hostname]}#{i}"
			vbx.memory = machine[:memory]
			vbx.cpus   = machine[:cpus]
			end

			master.vm.provision "ansible" do |ansible|
			ansible.playbook = "#{ANSIBLE_BASE_PATH}/master.yaml"
			ansible.extra_vars = {
						k8s_cluster_name: K8S_NAME,
						k8s_key_version: K8S_KEY_VERSION,
						k8s_master_admin_user: "vagrant",
						k8s_master_admin_group: "vagrant",
						k8s_master_node_name: "#{machine[:hostname]}#{i}",
						k8s_master_apiserver_advertise_address: "#{IP_BASE}#{i + 11}",
						k8s_master_apiserver_cert_extra_sans: "#{IP_BASE}#{i + 11}",                    
						k8s_master_node_ip: "#{IP_BASE}#{i + 11}",
						k8s_master_pod_network_cird: "192.168.0.0/16",
						k8s_tools_version: K8S_TOOLS_VERSION,
						os_version: OS_VERSION,
						crio_version: CRIO_VERSION,
						calico_version: CALICO_VERSION
					}
			end
		end
	end

	WORKERS.to_enum.with_index(1).each do |node, j|
		config.vm.define "#{node[:hostname]}#{j}" do |worker|
			worker.vm.box = node[:box]
			worker.vm.network "private_network", ip: "#{IP_BASE}#{j + 10 + MASTERS.length()}"
			worker.vm.hostname = "#{node[:hostname]}#{j}"

			worker.vm.provider "virtualbox" do |vbx|
			vbx.name   = "#{node[:hostname]}#{j}"
			vbx.memory = node[:memory]
			vbx.cpus   = node[:cpus]
			end
			
			worker.vm.provision "ansible" do |ansible|
			ansible.playbook = "#{ANSIBLE_BASE_PATH}/worker.yaml"
			ansible.extra_vars = {
						k8s_cluster_name: K8S_NAME,
						k8s_key_version: K8S_KEY_VERSION,
						k8s_node_admin_user:  "vagrant",
						k8s_node_admin_group: "vagrant",
						k8s_node_name: "#{node[:hostname]}#{j}",
						k8s_node_ip: "#{IP_BASE}#{j + 10 + MASTERS.length()}",
						k8s_tools_version: K8S_TOOLS_VERSION,
						os_version: OS_VERSION,
						crio_version: CRIO_VERSION
					}
			end
		end  
	end

end
