apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://server_prometheus:9090 
    isDefault: true
    access: proxy
    editable: true
  - name: InfluxDB
    version: 2
    type: influxdb
    access: proxy
    url: http://server_influxdb:8086
    jsonData:
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
      httpMode: POST
      organization: $DOCKER_INFLUXDB_INIT_ORG
      version: Flux
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN