# -*- mode: ruby -*-
# vi: set ft=ruby :

UBUNTU_BOX    = "bento/ubuntu-22.04"
PROVIDER      = "virtualbox"
PROVISION_SHELL = "shell"
VM_HOSTNAME   = "server-docker"
VM_IP_ADDRESS = "192.168.56.10"

Vagrant.configure("2") do |config|
  config.vm.box = UBUNTU_BOX
  config.vm.hostname = VM_HOSTNAME
  config.vm.network "private_network", ip: VM_IP_ADDRESS
  config.vm.synced_folder "shared/", "/app/shared"

  config.vm.provider PROVIDER do |vb|
    vb.name   = VM_HOSTNAME
    vb.memory = 6144
    vb.cpus   = 4
  end

  config.vm.provision PROVISION_SHELL do |shell|
    shell.path = "scripts/bootstrap.sh"
  end
end
