#######################################################################
#
# Basic Traefik Configuration(Static)
# @Author : Wilman Ortiz
# @Copyright (c) developer.io
#
#######################################################################
global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  mysql:
    address: ":3306"
  postgres:
    address: ":5432"
